### ISSUE TITLE
[Bug]: Filled buckets dont work with kubejs

### ISSUE THREAD

**Issue by RemagOfficial** [cech12/WoodenBucket#23]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Mod Version

2.1.0.0

### Describe the Issue

i want to change a recipe for a cobblestone generator to use the wooden buckets of lava and water with kubejs but they just show in the recipe as empty buckets even though im including the NBT for the fluid type.

**Comment by cech12** [comment]
Please try the ingredient types of the wiki page: https://github.com/cech12/BucketLib/wiki/Datapack-Recipes

**Comment by RemagOfficial** [comment]
so I have to use JSON recipes to use the filled buckets?

**Comment by cech12** [comment]
It is possible to change/add custom recipes with KubeJS: https://kubejs.com/wiki/tutorials/recipes#custom-modded-json-recipes

**Comment by RemagOfficial** [comment]
I know how to use kubejs, I don't want to use a json recipe I want to just use event.shaped like all the other recipes in my pack

**Comment by cech12** [comment]
If there is no possibility to add custom ingredients to shaped recipes via KubeJS "event.shaped"? Then there is no other way

**Comment by RemagOfficial** [comment]
I didn't make a bug report just to be told what I already know, I made it so it can be fixed like even if you just added a tag for filled buckets like #bucketlib:water_bucket and that tag includes the vanilla bucket and the wooden and ceramic ones and same for the other fluids the mods support

**Comment by cech12** [comment]
Sorry, but I don't know what you are knowing and what not ;) I am trying to help you here. :)

It is not a bug for me, because everything you try to achieve (adding a BucketLib bucket to a recipe) is possible right now with the mentioned things I linked above.

To be highly compatible with the large amount of fluid mods, the filled buckets are realized with NBT data and are not extra items. So, adding them to an item tag is not possible.

Therefore the mentioned custom ingredient types were invented to make it easier to add the buckets to recipes. These can be added to a recipe by the "event.custom" method.

I think, your request, adding custom ingredient types to recipes with methods like "event.shaped", is better placed at KubeJS's GitHub.

If you have any further questions. Please let me know and I try my best to help you.
